-- Only for an empty isolated test database; no production data is imported.
CREATE TABLE clients(id INTEGER PRIMARY KEY,timezone TEXT NOT NULL,processing_enabled BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE employees(client_id INTEGER NOT NULL REFERENCES clients(id),extension TEXT NOT NULL,telegram_user_id BIGINT,role TEXT NOT NULL,full_name TEXT,PRIMARY KEY(client_id,extension));
CREATE TABLE calls(id BIGSERIAL PRIMARY KEY,client_id INTEGER NOT NULL REFERENCES clients(id),extension TEXT,transcript TEXT,status TEXT DEFAULT 'analyzed',call_started_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE astra_analysis(call_id BIGINT PRIMARY KEY REFERENCES calls(id),score INTEGER,level TEXT);
CREATE TABLE astra_daily_spend(client_id INTEGER,day DATE,spent_units NUMERIC(16,4),PRIMARY KEY(client_id,day));
CREATE TABLE tasks(id BIGSERIAL PRIMARY KEY,type TEXT NOT NULL,client_id INTEGER REFERENCES clients(id),input JSONB NOT NULL,dedup_key TEXT,status TEXT DEFAULT 'new',run_after TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),result JSONB,UNIQUE(type,dedup_key));
CREATE TABLE training_sessions(id BIGSERIAL PRIMARY KEY,client_id INTEGER NOT NULL REFERENCES clients(id),extension TEXT NOT NULL,assigned_by TEXT,topic TEXT,scenario_kind TEXT,mode TEXT DEFAULT 'dialog',status TEXT DEFAULT 'active' CHECK(status IN ('active','completed','abandoned','failed')),transcript JSONB DEFAULT '[]',drill_state JSONB DEFAULT '{}',turns_count INTEGER DEFAULT 0,cost_usd NUMERIC DEFAULT 0,is_test BOOLEAN DEFAULT false,score INTEGER,level TEXT,analysis JSONB,error TEXT,started_at TIMESTAMPTZ DEFAULT now(),ended_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE pending_train_assignments(id BIGSERIAL PRIMARY KEY,client_id INTEGER REFERENCES clients(id),extension TEXT,consumed BOOLEAN DEFAULT false);
